### ISSUE TITLE
cannot import name '_get_dataset_dir' from 'nilearn.datasets.utils' (/opt/conda/lib/python3.11/site-packages/nilearn/datasets/utils.py)

### ISSUE THREAD

**Issue by stebo85** [cosanlab/nltools#444]
Dear nltools team,

It seems nltools  0.5.1 is currently not working with nilearn 0.10.4 under Python 3.11.6. The error I get when running:
```
from nltools import *
```

is 
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[30], line 1
----> 1 from nltools import *

File /opt/conda/lib/python3.11/site-packages/nltools/datasets.py:25
     23 import pandas as pd
     24 from nltools.data import Brain_Data
---> 25 from nilearn.datasets.utils import _get_dataset_dir, _fetch_file
     26 from pynv import Client
     28 # Optional dependencies

ImportError: cannot import name '_get_dataset_dir' from 'nilearn.datasets.utils' (/opt/conda/lib/python3.11/site-packages/nilearn/datasets/utils.py)
```

**Comment by stebo85** [comment]
If anyone else runs into this problem, before this toolbox is fixed, this is a combination of older dependency versions that works with Python 3.11.6:
```
pip install nltools==0.4.7 nilearn==0.10.2 scipy==1.11.4
```

**Comment by ejolly** [comment]
Fixed in v0.6.0 - updated to nilearn 0.10+ API, no longer uses deprecated _get_dataset_dir.

**Comment by stebo85** [comment]
Thank you so much!!!!!
