### ISSUE TITLE
create_sphere() probelm

### ISSUE THREAD

**Issue by Forrestwang1** [cosanlab/nltools#357]
Hi all,
I tried to use this function to make a mask, my understanding is I can put a list of centers but I got some error. The below is example code, when running the code, I got the error. 
'AttributeError: '_io.BytesIO' object has no attribute 'mode'
any suggestion? Thanks~

`from nltools.mask import create_sphere

mask = create_sphere([[-36,-56,-18],[0,0,0]], radius=3)`

**Comment by ljchang** [comment]
Hi @Forrestwang1, sorry I missed this. Can you share what version of nltools you are using? and the type of computer you are using? Your code works on my mac running nltools 0.4.2.

**Comment by ejolly** [comment]
Related to #365

**Comment by ejolly** [comment]
Resolved in v0.6.0. `create_sphere` was rewritten to construct `Nifti1Image` objects directly (no BytesIO round-trip), which removes the old `'_io.BytesIO' object has no attribute 'mode'` error. Float and multi-coordinate radii are now handled and covered by a test. Closing as fixed.
